version: '2'
services:
  web:
    image: odoo-srank:1.0
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    restart: always
